language: node_js

node_js:
  - "node"

script:
  - npm test

before_deploy:
  - npm run build

deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_token: "$NPM_TOKEN"
  cleanup: false
  on:
    branch: release

cache:
  directories:
    - node_modules
  sudo: false

